image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y libjpeg libjpeg-dev
  - npm install tamago

pages:
  stage: deploy
  script:
    - ./node_modules/tamago/bin/tamago.js build
  artifacts:
    paths:
    - public
  only:
    - master
