image: node:latest

before_script:
  - npm install tamago

pages:
  stage: deploy
  script:
    - uname -a
    - ./node_modules/tamago/bin/tamago.js build
  artifacts:
    paths:
    - public
  only:
    - master
