# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mettray Éditions
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mettray.com" # the base hostname & protocol for your site

# Sass
sass:
  sass_dir: css/
  style: compressed

# Default Layout
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

# Sitemap.xml
sitemap:
    file: "/sitemap.xml"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "laquo", "raquo"] # http://stackoverflow.com/questions/25596792/how-do-i-turn-off-smart-quotes-in-jekyll#25597026
